table Products
	lineageTag: edb21a89-2c6e-4158-ac99-87e5c430c1ed

	measure AVG_Retail_Price = AVERAGE(Products[ProductPrice])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fac2a856-fafd-48d5-be06-9bb76a314d92

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 2368042f-63f2-4552-9077-113590d125df
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 89d21482-f66d-4774-aa64-2e37f35b632d
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSKU
		dataType: string
		lineageTag: 0df491a2-56f0-48eb-a82c-ced0e98a3001
		summarizeBy: none
		sourceColumn: ProductSKU

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 9e881c91-eee7-4bab-b228-d3fc2f10df75
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: fad28c76-7a5e-428d-a6e8-7bc3fe1ac6eb
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: d6d774d0-2b45-49c8-ab88-0801121ed487
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column ProductColor
		dataType: string
		lineageTag: 8cb20fa2-6ae4-4d83-914d-2d9afc4f0fb5
		summarizeBy: none
		sourceColumn: ProductColor

		annotation SummarizationSetBy = Automatic

	column ProductSize
		dataType: string
		lineageTag: cf9acbdc-26e8-43bd-85a3-7a189dd69083
		summarizeBy: none
		sourceColumn: ProductSize

		annotation SummarizationSetBy = Automatic

	column ProductStyle
		dataType: string
		lineageTag: abbd4260-4676-4927-a005-0e06a5fffe21
		summarizeBy: none
		sourceColumn: ProductStyle

		annotation SummarizationSetBy = Automatic

	column ProductCost
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 98a4d0c9-06d4-4114-b9f6-aab07027c91a
		summarizeBy: sum
		sourceColumn: ProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column ProductPrice
		dataType: double
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: e5402af0-b9bd-48a2-b291-0aec3844bd9f
		summarizeBy: sum
		sourceColumn: ProductPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Anas Ali Khan\Data Analysis\DVA\C18\Data Source - 1782200922814\Data Source\AdventureWorks_Products.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductSKU", type text}, {"ProductName", type text}, {"ModelName", type text}, {"ProductDescription", type text}, {"ProductColor", type text}, {"ProductSize", type text}, {"ProductStyle", type text}, {"ProductCost", type number}, {"ProductPrice", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ProductCost", Currency.Type}, {"ProductPrice", Currency.Type}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"ProductPrice", type number}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

